quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,OPTIONS
quarkus.package.jar.type=uber-jar
quarkus.log.level=INFO
quarkus.log.category."org.gautelis".level=DEBUG
